### PR TITLE
Be consistent in the way alarm clusters are defined

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]

**Comment by elemoine** [comment]
@simonpasquier the downside of the splitting is that we emit more statues to Nagios.

**Comment by simonpasquier** [comment]
@elemoine sure but this is at least consistent with the other formulas and more logical.

**Comment by elemoine** [comment]
> @elemoine sure but this is at least consistent with the other formulas and more logical.

Yes, we could possibly set `alerting` to `disabled` for the `glusterfs_check` cluster.

**Comment by simonpasquier** [comment]
This is required for https://github.com/tcpcloud/salt-formula-heka/pull/96.

**Comment by elemoine** [comment]
Tested, and works as expected.

Note that we still have an issue with the monitoring of glusterfs. The collectd logs include the following:

```
[2016-12-08 08:57:58] glusterfs: Failed to execute 'gluster volume'
[2016-12-08 08:58:28] Command '['/usr/sbin/gluster', 'volume', 'status', 'all', 'detail']' failed (return code 2): Another transaction could be in progress. Please try again after sometime.

[2016-12-08 08:58:28] glusterfs: Failed to execute 'gluster volume'
[2016-12-08 08:58:48] Command '['/usr/sbin/gluster', 'volume', 'status', 'all', 'detail']' failed (return code 2): Another transaction is in progress. Please try again after sometime.
```

But that issue is not related to the alarm definitions.

**Pull request merged**
